version: '3.8'

services:
  toolbox:
    build:
      context: ./app
      args:
        APP_VERSION: ${APP_VERSION:-3.2.0-final}
    container_name: n8n-toolbox-app
    restart: unless-stopped
    env_file:
      - .env
    # This command uses the variable from the .env file to configure Uvicorn
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers ${UVICORN_WORKERS:-3}
    networks:
      - caddy_net

  caddy:
    image: caddy:2
    container_name: toolbox-caddy-proxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net

networks:
  caddy_net:

volumes:
  caddy_data:
  caddy_config: